### ISSUE TITLE
IRC Custom Reward ID

### ISSUE THREAD

**Issue by Sekoree** [Foretack/MiniTwitch#73]
Firstly, love this library, great work!

Would it be possible to add the custom reward ID (GUID?) from channel reward redeems that require a message?
I see its implemented in Helix but it's sent on IRC too.
The sum for the Tag is ``159093``
I added it for myself because I needed it, but I could make a PR if it's fine.
If yes, should it be just a string or a GUID on the ``Privmsg`` model?

**Comment by Foretack** [comment]
Hi, I was not aware of this tag's existence which is why it isn't added. Feel free to open a PR if you wish.

As for whether it should be a string or guid: I am not opposed to have it as a GUID, but I feel like it should be a string for the sake of consistency with other tags.

I am open to switching "id" tags to guids in the future to save memory (unless if there is performance regression)

**Comment by Foretack** [comment]
Merged in #74. Thanks again!
